# Chroma Vector Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma-server
  namespace: llmops-enterprise
  labels:
    app: chroma-server
    component: vector-database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chroma-server
  template:
    metadata:
      labels:
        app: chroma-server
    spec:
      containers:
        - name: chroma
          image: chromadb/chroma:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: CHROMA_SERVER_HOST
          value: "0.0.0.0"
        - name: CHROMA_SERVER_HTTP_PORT
          value: "8081"
            - name: CHROMA_DB_IMPL
              value: "duckdb+parquet"
            - name: PERSIST_DIRECTORY
              value: "/chroma/chroma"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: chroma-data
              mountPath: /chroma
        livenessProbe:
          httpGet:
            path: /api/v2/heartbeat
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v2/heartbeat
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
        - name: chroma-data
          persistentVolumeClaim:
            claimName: chroma-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: llmops-enterprise
  labels:
    app: chroma-server
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: chroma-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data-pvc
  namespace: llmops-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
# Weaviate Vector Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate-server
  namespace: llmops-enterprise
  labels:
    app: weaviate-server
    component: vector-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate-server
  template:
    metadata:
      labels:
        app: weaviate-server
    spec:
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:1.21.6
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_DATA_PATH
              value: "/var/lib/weaviate"
            - name: DEFAULT_VECTORIZER_MODULE
              value: "none"
            - name: ENABLE_MODULES
              value: "text2vec-openai,text2vec-cohere,text2vec-huggingface"
            - name: CLUSTER_HOSTNAME
              value: "node1"
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - name: weaviate-data
              mountPath: /var/lib/weaviate
          livenessProbe:
            httpGet:
              path: /v1/meta
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/meta
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: weaviate-data
          persistentVolumeClaim:
            claimName: weaviate-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate-service
  namespace: llmops-enterprise
  labels:
    app: weaviate-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: weaviate-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-data-pvc
  namespace: llmops-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
